package com.eventara.common.dto;
import jakarta.validation.constraints.NotBlank;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;

public class EventRequest {

    //required fields
    @NotBlank(message = "eventType is required (e.g., 'payment.failed')")
    private String eventType;

    @NotBlank(message = "source is required (e.g:, 'payment-service')")
    private String source;

    //optional fields - these will be autogenerated if not provided
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = "UTC")
    private Instant timestamp;

    // more optional fields
    private String userId;
    private String sessionId;
    private String severity; // will convert this to enum
    private Map<String, String> tags = new HashMap<>();
    private Map<String, Object> metadata = new HashMap<>();

    public EventRequest(){
        this.timestamp = Instant.now();
    }

    public String getEventType() {
        return eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Instant getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Instant timestamp) {

        this.timestamp = timestamp != null ? timestamp: Instant.now();
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public Map<String, String> getTags() {
        return tags;
    }

    public void setTags(Map<String, String> tags) {
        this.tags = tags;
    }

    public Map<String, Object> getMetadata() {
        return metadata;
    }

    public void setMetadata(Map<String, Object> metadata) {
        this.metadata = metadata;
    }
}
